create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "room_pass" smallint,
    "user_id" bigint,
    "user_name" text,
    "message" text,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."room" (
    "pass" smallint generated by default as identity not null,
    "name" text,
    "is_open" boolean,
    "update_at" timestamp with time zone not null default now()
);


create table "public"."user" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "icon" text,
    "latitude" numeric,
    "longitude" numeric,
    "altitude" numeric,
    "room_pass" smallint,
    "role" text,
    "distance" numeric,
    "update_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX room_pkey ON public.room USING btree (pass);

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."room" add constraint "room_pkey" PRIMARY KEY using index "room_pkey";

alter table "public"."user" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."messages" add constraint "messages_room_pass_fkey" FOREIGN KEY (room_pass) REFERENCES room(pass) not valid;

alter table "public"."messages" validate constraint "messages_room_pass_fkey";

alter table "public"."messages" add constraint "messages_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id) not valid;

alter table "public"."messages" validate constraint "messages_user_id_fkey";

alter table "public"."user" add constraint "user_room_pass_fkey" FOREIGN KEY (room_pass) REFERENCES room(pass) not valid;

alter table "public"."user" validate constraint "user_room_pass_fkey";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."room" to "anon";

grant insert on table "public"."room" to "anon";

grant references on table "public"."room" to "anon";

grant select on table "public"."room" to "anon";

grant trigger on table "public"."room" to "anon";

grant truncate on table "public"."room" to "anon";

grant update on table "public"."room" to "anon";

grant delete on table "public"."room" to "authenticated";

grant insert on table "public"."room" to "authenticated";

grant references on table "public"."room" to "authenticated";

grant select on table "public"."room" to "authenticated";

grant trigger on table "public"."room" to "authenticated";

grant truncate on table "public"."room" to "authenticated";

grant update on table "public"."room" to "authenticated";

grant delete on table "public"."room" to "service_role";

grant insert on table "public"."room" to "service_role";

grant references on table "public"."room" to "service_role";

grant select on table "public"."room" to "service_role";

grant trigger on table "public"."room" to "service_role";

grant truncate on table "public"."room" to "service_role";

grant update on table "public"."room" to "service_role";

grant delete on table "public"."user" to "anon";

grant insert on table "public"."user" to "anon";

grant references on table "public"."user" to "anon";

grant select on table "public"."user" to "anon";

grant trigger on table "public"."user" to "anon";

grant truncate on table "public"."user" to "anon";

grant update on table "public"."user" to "anon";

grant delete on table "public"."user" to "authenticated";

grant insert on table "public"."user" to "authenticated";

grant references on table "public"."user" to "authenticated";

grant select on table "public"."user" to "authenticated";

grant trigger on table "public"."user" to "authenticated";

grant truncate on table "public"."user" to "authenticated";

grant update on table "public"."user" to "authenticated";

grant delete on table "public"."user" to "service_role";

grant insert on table "public"."user" to "service_role";

grant references on table "public"."user" to "service_role";

grant select on table "public"."user" to "service_role";

grant trigger on table "public"."user" to "service_role";

grant truncate on table "public"."user" to "service_role";

grant update on table "public"."user" to "service_role";


