name: Reset Supabase Tables Daily

on:
  schedule:
    # 毎日0時にトリガー
    - cron: "0 0 * * *"  # UTC時間で0:00
  workflow_dispatch:  # 手動トリガーを可能にするオプション

jobs:
  reset_supabase_tables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'  # Node.js のバージョンを設定

      - name: Install dependencies
        run: |
          npm install
          npm install -g typescript

      - name: Compile TypeScript
        run: tsc resetSupabaseTables.ts --outDir dist  # TypeScriptファイルをコンパイル

      - name: Run Supabase table reset script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node dist/resetSupabaseTables.js
